####################################################################
# Apt update
####################################################################
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

####################################################################
# Setup user
####################################################################
- name: Create user
  user:
    name: '{{ ir_user }}'
    shell: /bin/bash

- name: Set user password
  shell: echo "{{ ir_user }}:{{ ir_passwd }}" | chpasswd

- name: Copy dns script
  copy:
    src: conf/dns_blacklist.sh
    dest: /home/{{ ir_user }}/dns_blacklist.sh
    owner: root
    group: root
    mode: '0755'

# Quick and dirty modification. Not proud of this :/
- name: Modify sudoers
  lineinfile:
    dest: '/etc/sudoers'
    line: '{{ ir_user }} ALL=NOPASSWD: /bin/systemctl restart bind9.service'
    insertafter: '^%sudo'

- name: Enable SSH password auth
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication yes'

- name: Restart SSH
  service:
    name: ssh
    state: restarted
    enabled: yes

####################################################################
# Install/Setup BIND 9 DNS server
####################################################################
- name: Install BIND
  package:
    name: '{{ item }}'
    state: latest
  with_items:
    - vim 
    - curl 
    - wget 
    - net-tools 
    - bind9 
    - bind9utils 
    - bind9-doc 
    - dnsutils 
    - tcpdump

- name: Copy named.conf
  template:
    src: conf/bind/named.conf
    dest: /etc/bind/named.conf

- name: Create /etc/bind/zones directory
  file:
    path: /etc/bind/zones
    owner: bind
    group: bind
    state: directory

- name: Copy zones
  template:
    src: conf/bind/blockeddomains.db
    dest: /etc/bind/zones/blockeddomains.db

- name: Get root hints file
  get_url:
    url: http://www.internic.net/domain/named.root
    dest: /etc/bind/root.servers
    mode: 0440

- name: Chown it bind dir
  file:
    path: /etc/bind
    owner: bind
    group: bind
    recurse: yes

# ir_user needs editing access
- name: Copy blacklist
  template:
    src: conf/bind/blacklisted.zones
    dest: /etc/bind/zones/blacklisted.zones
    owner: '{{ ir_user }}'
    group: bind

- name: Restart bind server
  service:
    name: bind9
    state: restarted
    enabled: yes

####################################################################
# Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Setup DNS demo - {{ ansible_nodename }}'
    channel: "{{ slack_channel }}"
  when: slack_token != None