crypto:
  cert: conf/cert.pem
  key: conf/key.pem
server:
  host: 0.0.0.0
  https: true
  port: 8888
users:
- name: '{{ caldera_user }}'
  password: '{{ caldera_pass }}'
proxy:
  default:
    cert: ''
    http: ''
    https: ''