version: '3.3'
services:
  dvwa:
    build: .
    restart: always
    ports:
      - "8080:80"
      - "5000:22"
    volumes:
      - dvwa-logs:/var/log
  dvwa_attack:
    build: .
    restart: always
    ports:
      - "9999:80"
    volumes:
      - dvwa-logs-attack:/var/log

volumes:
  dvwa-logs:
  dvwa-logs-attack:
