- hosts: caldera
  become: yes
  become_user: root
  tasks:
    - import_tasks: roles/caldera/setup_docker.yml
    - import_tasks: roles/caldera/setup_caldera.yml
    - import_tasks: roles/caldera/setup_user.yml
