version: '3.3'
services:
  dvwa:
    build: .
    restart: unless-stopped
    ports:
      - "8080:80"
      - "5000:22"
    networks:
      - default
      - backend
    volumes:
      - dvwa-logs:/var/log
    restart: unless-stopped
  mongo:
    image: mongo:3
    restart: unless-stopped
    volumes:
      - graylog-mongo-data:/data/db
    networks:
      - backend
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.12
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/security-settings.html#general-security-settings
      - xpack.security.enabled=false
      #- bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    volumes:
      - graylog-es-data:/usr/share/elasticsearch/data
    networks:
      - backend
  graylog:
    image: graylog/graylog:2.4
    environment:
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    depends_on:
      - mongo
      - elasticsearch
    links:
      - mongo
      - elasticsearch
    ports:
      # Beats
      - 5044:5044
    networks:
      - backend
    restart: unless-stopped
    volumes:
      - graylog-graylog-journal:/usr/share/graylog/data/journal
      - graylog-graylog-config:/usr/share/graylog/data/config
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    networks:
      - default
      - backend
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

volumes:
  dvwa-logs:
  dvwa-logs-attack:
  graylog-es-data:
  graylog-mongo-data:
  graylog-graylog-journal:
  graylog-graylog-config:

networks:
  backend:
  frontend: